services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

# Sources used:
#   https://docs.docker.com/compose/compose-file/
